var privacylabel_languages = {
"code":{
  "collection": "2",
  "section_collection_explanation": " ",
  "learn_more": "learn more",
  "receive_from_you": "Y",
  "aggregated_data": "A",
  "personal_data": "B",
  "sensitive_data": "C",
  "receive_from_others": "R",
  "observe": "O",
  "create": "T",
  "purchase": "P",
  "location": "3",
  "section_location_explanation": " ",
  "all_data": "F",
  "most_data": "E",
  "some_data": "D",
  "a_little_data": "C",
  "least_amount_of_data": "B",
  "no_data": "B",
  "processed_outside_the_eu": "is processed outside the EU",
  "duration": "4",
  "section_duration_explanation": " ",
  "1_year_or_less": "B",
  "1_month_or_less": "A",
  "10_years_or_less": "C",
  "more_than_10_years": "D",
  "purpose": "5",
  "section_purpose_explanation": " ",
  "human_resources": "U",
  "providing_goods_and_services": "P",
  "scientific_research": "R",
  "financial_administration": "I",
  "health_care": "H",
  "crime_and_national_security": "C",
  "security_and_surveillance": "S",
  "marketing_or_sales_or_customer_relations": "M",
  "authorisation_management": "A",
  "judicial": "J",
  "education": "E",
  "automated_decision_making": "D",
  "fraud_detection_and_prevention": "F",
  "legal": "6",
  "section_legal_explanation": " ",
  "legal_obligation": "L",
  "contract": "T",
  "consent": "S",
  "legitimate_interests": "I",
  "vital_interests": "V",
  "public_task": "P",
  "sharing": "7",
  "section_sharing_explanation": " ",
  "customers": "C",
  "parent_or_daughter_or_sibling_organisation": "O",
  "processors": "P",
  "advertisers": "V",
  "government": "G",
  "third_parties": "T",
  "partners": "A",
  "service_providers": "S",
  "action": "Take action",
  "section_action_explanation": " ",
  "read_our_privacy_policy": "Read our privacy statement",
  "manage_your_data": "Manage your data",
  "contact_our_privacy_officer": "Contact our privacy representative",
  "email": "email",
  "phone": "phone",
  "last_updated": "Last updated",
  "version": "version"
},
"de":{
  "collection": "Erhebung von Daten",
  "section_collection_explanation": "Die Daten, die Sie explizit teilen. Aber auch die Sammlung von Daten über Ihr Verhalten und Daten aus anderen Quellen. Daten haben verschiedene Sensibilitätsstufen. Sie umfassen: \"aggregierte Daten\" (z. B. das durchschnittliche Einkommensniveau in einer Vorwahl), personenbezogene Daten (die sich direkt auf eine Person beziehen, z. B. eine Adresse) und sensible personenbezogene Daten (z. B. Details über Gesundheit oder Religionszugehörigkeit).",
  "learn_more": "Mehr erfahren",
  "receive_from_you": "Wir erhalten von Ihnen",
  "aggregated_data": "Aggregierte Daten",
  "personal_data": "Personenbezogene Daten",
  "sensitive_data": "Sensible personenbezogene Daten",
  "receive_from_others": "Wir erhalten von anderen",
  "observe": "Wir beobachten",
  "create": "Wir erstellen",
  "purchase": "Wir kaufen",
  "location": "Standort",
  "section_location_explanation": "Wenn Daten über Sie außerhalb der Europäischen Union verarbeitet werden, können die Daten einem niedrigeren Schutzniveau unterliegen.",
  "all_data": "Alle Daten",
  "most_data": "Die meiste Daten",
  "some_data": "Einige Daten",
  "a_little_data": "Wenige Daten",
  "least_amount_of_data": "Sehr wenige Daten",
  "no_data": "Keine Daten",
  "none": "Keine",
  "processed_outside_the_eu": "werden außerhalb der EU verarbeitet",
  "duration": "Dauer der Speicherung",
  "section_duration_explanation": "Personenbezogene Daten sollten nicht länger als nötig gespeichert werden. In Europa ist dies gesetzlich vorgeschrieben.",
  "1_year_or_less": "Ein Jahr oder weniger",
  "1_month_or_less": "Einen Monat oder weniger",
  "10_years_or_less": "Zehn Jahre oder weniger",
  "more_than_10_years": "Mehr als zehn Jahre",
  "purpose": "Zweck",
  "section_purpose_explanation": "Wenn personenbezogene Daten erhoben werden, sollte der Zweck immer klar und spezifisch sein. Die Daten dürfen nicht für andere Zwecke verwendet werden, als für die sie ursprünglich erhoben wurden.",
  "human_resources": "Personalwesen",
  "providing_goods_and_services": "Bereitstellung von Waren und Dienstleistungen",
  "scientific_research": "Wissenschaftliche Forschung",
  "financial_administration": "Finanzielle Verwaltung",
  "health_care": "Gesundheit und Medizin",
  "crime_and_national_security": "Kriminalitätsbekämpfung und nationale Sicherheit",
  "security_and_surveillance": "Sicherheit und Überwachung",
  "marketing_or_sales_or_customer_relations": "Marketing, Vertrieb und Kundenbetreuung",
  "authorisation_management": "Berechtigungsverwaltung",
  "judicial": "Rechtlich",
  "education": "Ausbildung",
  "automated_decision_making": "Automatisierte Entscheidungsfindung",
  "fraud_detection_and_prevention": "Betrugserkennung und -prävention",
  "legal": "Rechtmäßigkeit ",
  "section_legal_explanation": "Die Datenverarbeitung erfolgt immer auf einer bestimmten Rechtsgrundlage. Neben der Einwilligung gibt es fünf weitere Möglichkeiten, wie z. B. das Vorliegen eines Vertrages oder eine rechtliche Verpflichtung.",
  "legal_obligation": "Rechtliche Verplichtung",
  "contract": "Vertrag",
  "consent": "Einwilligung",
  "legitimate_interests": "Berechtigtes Interesse ",
  "vital_interests": "Lebenswichtige Interessen",
  "public_task": "Öffentliches Interesse",
  "sharing": "Weitergabe von Daten",
  "section_sharing_explanation": "Daten können mit anderen Organisationen geteilt werden. Zum Beispiel, um bestimmte Aufgaben auszulagern, um mit Partnern zusammenzuarbeiten, um Vorschriften einzuhalten oder als Teil einer Transaktion.",
  "customers": "Kunden",
  "parent_or_daughter_or_sibling_organisation": "Mutter- und Tochterunternehmen",
  "processors": "Verarbeiter",
  "advertisers": "Werbetreibende",
  "government": "Regierung",
  "third_parties": "Sonstige Dritte",
  "partners": "Partner",
  "service_providers": "Service providers",
  "action": "Aktion starten",
  "section_action_explanation": "Privacy Label bietet eine Zusammenfassung - lesen Sie die vollständige Datenschutzerklärung für detailliertere Informationen.",
  "read_our_privacy_policy": "Lesen Sie unsere Datenschutzerklärung",
  "manage_your_data": "Verwalten Sie Ihre Daten",
  "contact_our_privacy_officer": "Kontakt zu unserem Datenschutzbeauftragten",
  "email": "E-Mail",
  "phone": "Telefon",
  "last_updated": "Letzte Aktualisierung",
  "version": "Version"
},
"en-uk":{
  "collection": "Data collection",
  "section_collection_explanation": "The data that you explicitly share, but also data about your behaviour and data from other sources can be collected. In general data may have various levels of sensitivity, ranging from ‘aggregated data’ (for example, the average income level in an area code), to personal data (which is directly related to a person, such as an address), to sensitive personal data (such as details about health, sexual preference or religious affiliation). \n",
  "learn_more": "learn more",
  "receive_from_you": "receive from you",
  "aggregated_data": "aggregated data",
  "personal_data": "personal data",
  "sensitive_data": "sensitive personal data",
  "receive_from_others": "receive from others",
  "observe": "observe",
  "create": "create",
  "purchase": "purchase",
  "location": "location",
  "section_location_explanation": "If data about you is processed outside the European Union it may be subject to a lower level of protection.",
  "all_data": "all data",
  "most_data": "most data",
  "some_data": "some data",
  "a_little_data": "a little data",
  "least_amount_of_data": "the least amount",
  "no_data": "no data",
  "none": "none",
  "processed_outside_the_eu": "is processed outside the EU",
  "duration": "duration",
  "section_duration_explanation": "To minimise risk personal data should not be stored longer than necessary. In Europe this is a legal requirement.",
  "1_year_or_less": "one year or less",
  "1_month_or_less": "one month or less",
  "10_years_or_less": "ten years or less",
  "more_than_10_years": "more than ten years",
  "purpose": "Purpose",
  "section_purpose_explanation": "When data about people is collected, the purpose should always be clear and specific. The data may not be used for other purposes than it was initially collected for.",
  "human_resources": "human resources",
  "providing_goods_and_services": "Providing goods and services",
  "scientific_research": "Scientific research",
  "financial_administration": "financial administration",
  "health_care": "health care",
  "crime_and_national_security": "crime fighting and national security",
  "security_and_surveillance": "security and surveillance",
  "marketing_or_sales_or_customer_relations": "marketing, sales and customer relationship",
  "authorisation_management": "authorisation management",
  "judicial": "judicial",
  "education": "education",
  "automated_decision_making": "automated decision making",
  "fraud_detection_and_prevention": "fraud detection and prevention",
  "legal": "Legal grounds",
  "section_legal_explanation": "Data processing is always done on a specific legal foundation. Besides consent there are five other possibilities, such as having a contract or it being required by law.",
  "legal_obligation": "legal obligation",
  "contract": "contract",
  "consent": "consent",
  "legitimate_interests": "legitimate interest",
  "vital_interests": "vital interest",
  "public_task": "public task",
  "sharing": "Data sharing",
  "section_sharing_explanation": "Data may be shared with other organisations. For example to outsource certain tasks, to collaborate with partners, be compliant with regulations, or as part of a transaction.",
  "customers": "customers",
  "parent_or_daughter_or_sibling_organisation": "parent, daughter or sibling organisation",
  "processors": "processors",
  "advertisers": "advertisers",
  "government": "government",
  "third_parties": "other third parties",
  "partners": "partners",
  "service_providers": "service providers",
  "action": "Take action",
  "section_action_explanation": "A privacy label offers a summary - read the full privacy statement for more detailed information.",
  "read_our_privacy_policy": "read our privacy statement",
  "manage_your_data": "manage your data",
  "contact_our_privacy_officer": "contact our privacy representative",
  "email": "email",
  "phone": "phone",
  "last_updated": "last updated",
  "version": "version"
},
"es":{
  "collection": "Recolección de información",
  "section_collection_explanation": "La información que usted comparte explícitamente, información sobre su comportamiento e información de otras fuentes puede ser recolectada. En general la información podría tener varios niveles de sensibilidad, que van desde 'información o datos agregados'(por ejemplo, el promedio del nivel de ingresos asociado a un código postal), información personal (que está directamente relacionada a una persona, como una dirección postal), hasta información personal sensible (como detalles sobre salud, preferencia sexual o afiliación religiosa).",
  "learn_more": "aprenda más",
  "receive_from_you": "información recibida sobre usted",
  "aggregated_data": "información o datos agregados",
  "personal_data": "información personal",
  "sensitive_data": "información personal sensible",
  "receive_from_others": "información recibida sobre otros",
  "observe": "observar",
  "create": "crear",
  "purchase": "comprar",
  "location": "ubicación",
  "section_location_explanation": "Si información sobre usted es procesada fuera de la Unión Europea puede ser sujeta a un nivel inferior de protección",
  "all_data": "toda la información",
  "most_data": "la mayoría de la información",
  "some_data": "parte de la información",
  "a_little_data": "poca información",
  "least_amount_of_data": "la menor cantidad de información",
  "no_data": "ninguna información",
  "none": "ninguna",
  "processed_outside_the_eu": "es procesada fuera de la UE",
  "duration": "duración",
  "section_duration_explanation": "Para minimizar el riesgo de que la información sea almacenada más del tiempo necesario. En Europa ésto es un requerimiento legal.",
  "1_year_or_less": "un año o menos",
  "1_month_or_less": "un mes o menos",
  "10_years_or_less": "diez años o menos",
  "more_than_10_years": "más de diez años",
  "purpose": "Propósito",
  "section_purpose_explanation": "Cuando información personal es recolectada, el propósito siempre debe ser claro y específico. La información no puede ser usada para otro propósito más que por los cuales fue recolectada inicialmente. ",
  "human_resources": "recursos humanos",
  "providing_goods_and_services": "Proporcionar bienes y servicios",
  "scientific_research": "Investigación científica",
  "financial_administration": "administración financiera",
  "health_care": "cuidado de la salud",
  "crime_and_national_security": "lucha contra el crimen y seguridad nacional",
  "security_and_surveillance": "seguridad y vigilancia",
  "marketing_or_sales_or_customer_relations": "mercadeo, ventas y servicio al cliente",
  "authorisation_management": "gestión de autorización",
  "judicial": "judicial",
  "education": "educación",
  "automated_decision_making": "toma de decisiones automatizada",
  "fraud_detection_and_prevention": "detección y prevención de fraude",
  "legal": "Motivos legales",
  "section_legal_explanation": "El procesamiento de información siempre se hace sobre un fundamento legal específico. Además de consentimiento existen otras cinco posibilidades, como lo es un contrato o que sea un requerimiento legal.",
  "legal_obligation": "obligación legal",
  "contract": "contrato",
  "consent": "consentimiento",
  "legitimate_interests": "interés legítimo",
  "vital_interests": "interés vital",
  "public_task": "tarea pública",
  "sharing": "Compartir datos",
  "section_sharing_explanation": "La información podría ser compartida con otras organizaciones. Por ejemplo para delegar algunas tareas, para colaborar con socios, cumplir con regulaciones, o como parte de una transacción.",
  "customers": "clientes",
  "parent_or_daughter_or_sibling_organisation": "organización madre o hija",
  "processors": "procesadores",
  "advertisers": "anunciantes",
  "government": "gobiernos",
  "third_parties": "otros terceros",
  "partners": "socios",
  "service_providers": "proveedores de servicios",
  "action": "Tomar acción",
  "section_action_explanation": "Una etiqueta de privacidad ofrece un resumen - lea la política de privacidad completa para información más detallada",
  "read_our_privacy_policy": "lea nuestra política de privacidad",
  "manage_your_data": "administrar su información",
  "contact_our_privacy_officer": "contactar a nuestro representante de privacidad",
  "email": "correo electrónico",
  "phone": "teléfono",
  "last_updated": "última actualización",
  "version": "versión"
},
"fr":{
  "collection": "La collecte de données",
  "section_collection_explanation": "Les données que vous partagez explicitement, mais aussi les données sur votre comportement et les données provenant d'autres sources peuvent être collectées. En général, les données peuvent avoir différents niveaux de sensibilité, allant des \"données agrégées\" (par exemple, le niveau de revenu moyen dans un indicatif regional), aux données personnelles (tels que les détails sur la santé, la préférence sexuelle ou les affiliations religieuses).",
  "learn_more": "apprenez plus",
  "receive_from_you": "recevoir de vous",
  "aggregated_data": "données agrégées",
  "personal_data": "données personnelles",
  "sensitive_data": "données personnelles sensibles",
  "receive_from_others": "recevoir des autres",
  "observe": "observer",
  "create": "créer",
  "purchase": "achat",
  "location": "emplacement",
  "section_location_explanation": "Si les données vous concernant sont traitées en dehors de l'Union Européenne, elles peuvent faire l'objet d'un niveau de protection inférieur.",
  "all_data": "toutes les données",
  "most_data": "la plupart des données",
  "some_data": "quelques données",
  "a_little_data": "un peu de données",
  "least_amount_of_data": "la plus petite quantité",
  "no_data": "pas de données",
  "none": "aucune",
  "processed_outside_the_eu": "sont traitées en dehors de l'Union Européenne",
  "duration": "la durée",
  "section_duration_explanation": "Pour minimiser les risques, les données personnelles ne devraient pas être stockées plus longtemps que nécessaire. En Europe c'est une obligation légale.",
  "1_year_or_less": "un an ou moins",
  "1_month_or_less": "un mois ou moins",
  "10_years_or_less": "dix ans ou moins",
  "more_than_10_years": "plus de dix ans",
  "purpose": "Objectif",
  "section_purpose_explanation": "Lorsque les données sur les personnes sont collectées, l'objectif doit toujours être clair et spécifique. Les données ne peuvent pas être utilisées dans un autre but que celui pour lequel elles ont été collectées initialement.",
  "human_resources": "ressources humaines",
  "providing_goods_and_services": "fournir des biens et des services",
  "scientific_research": "recherche scientifique",
  "financial_administration": "administration financière",
  "health_care": "santé",
  "crime_and_national_security": "la lutte contre le crime et la sécurité nationale",
  "security_and_surveillance": "sécurité et surveillance",
  "marketing_or_sales_or_customer_relations": "marketing, ventes and relation client",
  "authorisation_management": "gestion des autorisations",
  "judicial": "judiciaire",
  "education": "éducation",
  "automated_decision_making": "prise de décision automatisée",
  "fraud_detection_and_prevention": "détection de fraude et prévention",
  "legal": "motifs juridiques",
  "section_legal_explanation": "Le traitement des données se fait toujours sur une base juridique spécifique. Outre le consentement, il existe cinq autres possiblités, comme avoir un contrat ou qu'il soit exigé par la loi.",
  "legal_obligation": "obligation légale",
  "contract": "contrat",
  "consent": "consentement",
  "legitimate_interests": "intérêt légitime",
  "vital_interests": "intérêt vital",
  "public_task": "tâche publique",
  "sharing": "Partage de données",
  "section_sharing_explanation": "Les données peuvent être partagées avec d'autres organisations. Par exemple, pour externaliser certaines tâches, pour collaborer avec des partenaires, être conformes aux régulations, ou dans le cadre d'une transaction.",
  "customers": "clients",
  "parent_or_daughter_or_sibling_organisation": "organisation de parents, filles ou de frères et soeurs  ",
  "processors": "processeurs",
  "advertisers": "publicitaires",
  "government": "gouvernement",
  "third_parties": "autres tierces parties",
  "partners": "partenaires",
  "service_providers": "prestataires de service",
  "action": "Agissez",
  "section_action_explanation": "Une étiquette de confidentialité est un résumé: lisez l'intégralité de la déclaration de confidentialité pour plus d'informations.",
  "read_our_privacy_policy": "lisez notre déclaration de confidentialité",
  "manage_your_data": "gérez vos données",
  "contact_our_privacy_officer": "contactez notre représentant en matière de confidentialité",
  "email": "email",
  "phone": "téléphone",
  "last_updated": "dernière mise à jour",
  "version": "version"
},
"fy":{
  "collection": "Sammele gegevens",
  "section_collection_explanation": "Alle ynformaasje dy't wat oer in libjend minske seit is in persoansgegeven. It giet dus om alle ynformaasje dy't dy, dy makket. Der binne gearfoege, gewoane en gefoelige persoansgegevens. Organisaasjes sammelje persoansgegevens op ferskate manieren.",
  "learn_more": "Mear datails",
  "receive_from_you": "Untfongen fan jo",
  "aggregated_data": "gearfoege gegevens",
  "personal_data": "persoanlike gegevens",
  "sensitive_data": "gefoelige persoanlike gegevens",
  "receive_from_others": "Untfongen fan oaren",
  "observe": "Observaasje",
  "create": "meitsje",
  "purchase": "keapje",
  "location": "Lokaasje",
  "section_location_explanation": "Persoansgegevens kinne op ferskate lokaasjes ferwurke wurde. Binnen de EU is de AVG fan tapassing. As gegevens oer jo bûten de EU ferwurke wurde, dan binne de wetten fan dat lân ek op dy gegevens fan tapassing.",
  "all_data": "alle gegevens",
  "most_data": "de measte gegevens",
  "some_data": "guon gegevens",
  "a_little_data": "inkelde gegevens",
  "least_amount_of_data": "sa min mooglik gegegvens",
  "no_data": "gjin gegevens",
  "none": "neat",
  "processed_outside_the_eu": "wurde bûten de EU ferwurke",
  "duration": "Tiidsrek",
  "section_duration_explanation": "Wannear persoansgegevens sammele binne, meie se net foar ivich bewarre wurde. De gouden rigel is: persoansgegevens meie net langer bewarre wurde as needsaaklik foar it doel wêrfoar se sammele binne.",
  "1_year_or_less": "ien jier of minder",
  "1_month_or_less": "ien moanne of minder",
  "10_years_or_less": "tsien jier of minder",
  "more_than_10_years": "mear as tsien jier",
  "purpose": "Doel",
  "section_purpose_explanation": "Wannear in organisaasje gegevens oer jo ferwurket hawwe se dêr in spesifyk doel foar nedich. Persoansgegevens meie net brûkt wurde foar oare doelen as wêrfoar se sammele binne.",
  "human_resources": "personiel en organisaasje",
  "providing_goods_and_services": "leverjen fan guod en tsjinsten",
  "scientific_research": "Wittenskiplik ûndersyk",
  "financial_administration": "finansjele administraasje",
  "health_care": "sûnenssoarch",
  "crime_and_national_security": "misdaadbestriding en nasjonale feilichheid",
  "security_and_surveillance": "befeiliging en surveillânse",
  "marketing_or_sales_or_customer_relations": "marketing, ferkeap en klantrelaasjes",
  "authorisation_management": "autorisaasjemanagement",
  "judicial": "juridysk",
  "education": "edukaasje",
  "automated_decision_making": "automatisearre beslútfoarming",
  "fraud_detection_and_prevention": "fraudedeteksje en -previnsje",
  "legal": "Juridyske grûnslach",
  "section_legal_explanation": "Foar elke ferwurking hat in organisaasje in spesifyk doel en in bepaalde grûnslach nedich. De grûnslach is de fundearring foar it ferwurkjen fan persoansgegevens ûnder de AVG. Der binne 6 grûnslaggen wêrop in ferwurking basearre wurde kin.",
  "legal_obligation": "wetlike ferplichting",
  "contract": "kontraktuele oerienkomst",
  "consent": "tastimming",
  "legitimate_interests": "rjochtfeardige belang",
  "vital_interests": "fitaal belang",
  "public_task": "publike taak",
  "sharing": "Dielde gegevens",
  "section_sharing_explanation": "Organisaasjes kinne ek persoansgegevens diele mei oare organisaasjes. Dat kin foar it útfieren fan in opdracht of foar in gearwurking wêze. Somtiden moatte gegevens dield wurde fan de oerheid, of kinne gegevens ferkocht wurde.",
  "customers": "ôfnimmers",
  "parent_or_daughter_or_sibling_organisation": "memme-, dochter- of susterorganisaasje",
  "processors": "ferwurkers",
  "advertisers": "advertearders",
  "government": "oerheden",
  "third_parties": "oare tredde partijen",
  "partners": "partners",
  "service_providers": "tsjinstleveransiers",
  "action": "Dit kinne jo dwaan",
  "section_action_explanation": "Wannear in organisaasje gegevens oer jo ferwurket hawwe jo rjocht op ynformaasje en oare grûnrjochten om kontrôle te hawwen oer jo gegevens. Der stiet in protte ynformaasje yn de privacyferklearring. Jo kinne ek kontakt opnimme mei de organisaasje.",
  "read_our_privacy_policy": "Lês ús privacyferklearring",
  "manage_your_data": "Behear jo gegevens",
  "contact_our_privacy_officer": "Nim kontakt op mei ús privacyferantwurdlike",
  "email": "e-mailadres",
  "phone": "telefoannûmer",
  "last_updated": "Lêst fernijd",
  "version": "ferzje"
},
"it":{
  "collection": "Raccolta dati",
  "section_collection_explanation": "Possono essere raccolti i dati che condividi esplicitamente, ma anche dati sul tuo comportamento e dati da altre fonti. In generale i dati possono avere vari livelli di sensibilità, che vanno dai `` dati aggregati '' (ad esempio, il livello di reddito medio in un prefisso), ai dati personali (che sono direttamente correlati a una persona, come un indirizzo), ai dati sensibili e personali (come dettagli sulla salute, preferenza sessuale o affiliazione religiosa).",
  "learn_more": "Per saperne di più",
  "receive_from_you": "Ricevuti da te",
  "aggregated_data": "dati aggregati",
  "personal_data": "dati personali",
  "sensitive_data": "dati personali e sensibili",
  "receive_from_others": "Ricevuti da altri",
  "observe": "Rilevati",
  "create": "Creati",
  "purchase": "Acquistati",
  "location": "Posizione",
  "section_location_explanation": "Se i dati che ti riguardano vengono elaborati al di fuori dell'Unione Europea, potrebbero essere soggetti a un livello di protezione inferiore.",
  "all_data": "tutti i dati",
  "most_data": "la maggior parte dei dati",
  "some_data": "alcuni dati",
  "a_little_data": "un po' di dati",
  "least_amount_of_data": "la quantità minima",
  "no_data": "nessun dato",
  "none": "niente",
  "processed_outside_the_eu": "vengono processati fuori l'Unione Europea",
  "duration": "durata",
  "section_duration_explanation": "Per ridurre al minimo il rischio, i dati personali non dovrebbero essere conservati più a lungo del necessario. In Europa questo è un requisito legale.",
  "1_year_or_less": "un anno o meno",
  "1_month_or_less": "un mese o meno",
  "10_years_or_less": "dieci anni o meno",
  "more_than_10_years": "più di dieci anni",
  "purpose": "Scopo",
  "section_purpose_explanation": "Quando vengono raccolti dati sulle persone, lo scopo dovrebbe essere sempre chiaro e specifico. I dati non possono essere utilizzati per scopi diversi da quelli per cui sono stati inizialmente raccolti.",
  "human_resources": "risorse umane",
  "providing_goods_and_services": "Fornitura di beni e servizi",
  "scientific_research": "Ricerca scientifica",
  "financial_administration": "amministrazione finanziaria",
  "health_care": "assistenza sanitaria",
  "crime_and_national_security": "lotta alla criminalità e sicurezza nazionale",
  "security_and_surveillance": "sicurezza e sorveglianza",
  "marketing_or_sales_or_customer_relations": "Marketing, vendite e relazione con i clienti",
  "authorisation_management": "gestione delle autorizzazioni",
  "judicial": "giudiziario",
  "education": "Formazione scolastica",
  "automated_decision_making": "processo decisionale automatizzato",
  "fraud_detection_and_prevention": "rilevamento e prevenzione delle frodi",
  "legal": "Motivi legali",
  "section_legal_explanation": "Il trattamento dei dati avviene sempre su una base giuridica specifica. Oltre al consenso ci sono altre cinque possibilità, come avere un contratto o essere richiesto dalla legge.",
  "legal_obligation": "Obbligazione legale",
  "contract": "contratto",
  "consent": "Consenso",
  "legitimate_interests": "Legittimo interesse",
  "vital_interests": "Interesse vitale",
  "public_task": "Compito pubblico",
  "sharing": "Condivisione dei dati",
  "section_sharing_explanation": "I dati possono essere condivisi con altre organizzazioni. Ad esempio, per esternalizzare determinate attività, collaborare con i partner, essere conforme alle normative o come parte di una transazione.",
  "customers": "clienti",
  "parent_or_daughter_or_sibling_organisation": "Organizzazione di genitore, figlia o fratelli",
  "processors": "Processori",
  "advertisers": "Inserzionisti",
  "government": "Governo",
  "third_parties": "Altre terze parti",
  "partners": "Partners",
  "service_providers": "Fornitori di servizi",
  "action": "Agire",
  "section_action_explanation": "Un'etichetta sulla privacy offre un riepilogo - leggi l'informativa sulla privacy completa per informazioni più dettagliate.",
  "read_our_privacy_policy": "leggi la nostra informativa sulla privacy",
  "manage_your_data": "gestisci i tuoi dati",
  "contact_our_privacy_officer": "contatta il nostro rappresentante per la privacy",
  "email": "email",
  "phone": "telefono",
  "last_updated": "ultimo aggiornamento",
  "version": "versione"
},
"nl":{
  "collection": "Verzamelde gegevens",
  "section_collection_explanation": "Data die u expliciet deelt, maar ook data over uw gedrag en data uit externe bronnen kan worden verzameld. Data kan verschillende gevoeligheidsniveaus hebben. Geaggregeerde data beschrijft mensen indirect, bijvoorbeeld als het gemiddelde inkomensniveau in uw woonwijk wordt gebruikt. Uw adres is persoonlijke data, terwijl details over gezondheid, sexualiteit of religie als gevoelige data worden beschouwd.",
  "learn_more": "meer details",
  "receive_from_you": "ontvangen van u",
  "aggregated_data": "geaggregeerde gegevens",
  "personal_data": "persoonsgegevens",
  "sensitive_data": "gevoelige persoonsgegevens",
  "receive_from_others": "ontvangen van anderen",
  "observe": "observeren",
  "create": "creëren",
  "purchase": "kopen",
  "location": "locatie",
  "section_location_explanation": "Wanneer data buiten de EU zone wordt verwerkt, dan kan het een lagere mate van juridische bescherming hebben.",
  "all_data": "all gegevens",
  "most_data": "de meeste gegevens",
  "some_data": "sommige gegevens",
  "a_little_data": "enkele gegevens",
  "least_amount_of_data": "de kleinste hoeveelheid",
  "no_data": "geen gegevens",
  "none": "geen",
  "processed_outside_the_eu": "worden buiten de EU verwerkt",
  "duration": "tijdsduur",
  "section_duration_explanation": "Data zou niet langer dan nodig moeten worden bewaard. In de Europese Unie is dit wettelijk verplicht.",
  "1_year_or_less": "een jaar of minder",
  "1_month_or_less": "een maand of minder",
  "10_years_or_less": "tien jaar of minder",
  "more_than_10_years": "meer dan tien jaar",
  "purpose": "Doel",
  "section_purpose_explanation": "Wanneer een organisatie gegevens over u verwerkt, hebben ze daar een specifiek doel voor nodig. Persoonsgegevens mogen niet worden gebruikt voor andere doelen dan waarvoor ze zijn verzameld.",
  "human_resources": "personeel en organisatie",
  "providing_goods_and_services": "Leveren van goederen en diensten",
  "scientific_research": "Wetenschappelijk onderzoek",
  "financial_administration": "financiële administratie",
  "health_care": "gezondheidszorg ",
  "crime_and_national_security": "misdaadbestrijding en nationale veiligheid",
  "security_and_surveillance": "beveiliging en surveillance",
  "marketing_or_sales_or_customer_relations": "marketing, sales en klantrelaties",
  "authorisation_management": "Autorisatiemanagement",
  "judicial": "juridisch",
  "education": "educatie",
  "automated_decision_making": "geautomatiseerde besluitvorming",
  "fraud_detection_and_prevention": "fraudedetectie en -preventie",
  "legal": "Juridische grondslag",
  "section_legal_explanation": "Voor iedere verwerking heeft een organisatie een specifiek doel en een bepaalde juridische grondslag nodig. Naast het hebben van toestemming zijn er nog vijf andere opties, zoals een contractuele overeenkomst of een wettelijke verplichting.",
  "legal_obligation": "wettelijke verplichting",
  "contract": "contractuele overeenkomst",
  "consent": "toestemming",
  "legitimate_interests": "gerechtvaardigd belang",
  "vital_interests": "vitaal belang",
  "public_task": "publieke taak",
  "sharing": "Gedeelde gegevens",
  "section_sharing_explanation": "Organisaties kunnen ook persoonsgegevens delen met andere organisaties. Dat kan voor het uitvoeren van een opdracht, of voor een samenwerking. Soms moeten gegevens worden gedeeld van de overheid of kunnen gegevens worden verkocht.",
  "customers": "Afnemers",
  "parent_or_daughter_or_sibling_organisation": "Moeder-, dochter- of zusterorganisatie",
  "processors": "Verwerkers",
  "advertisers": "Adverteerders",
  "government": "Overheden",
  "third_parties": "Andere derde partijen",
  "partners": "Partners",
  "service_providers": "Diensten leveranciers",
  "action": "Dit kunt u doen",
  "section_action_explanation": "Wanneer een organisatie gegevens over u verwerkt, hebt u recht op informatie en andere grondrechten om controle te hebben over uw gegevens. Er staat veel informatie in de privacyverklaring. U kunt ook contact opnemen met de organisatie.",
  "read_our_privacy_policy": "Lees onze privacyverklaring",
  "manage_your_data": "Beheer uw gegevens",
  "contact_our_privacy_officer": "Neem contact op met onze privacyverantwoordelijke",
  "email": "E-mailadres",
  "phone": "Telefoonnummer",
  "last_updated": "Bijgewerkt op",
  "version": "versie"
},
"ro":{
  "collection": "Date prelucrate",
  "section_collection_explanation": "Personal data is data that says something about you as an individual. In short: all the information that makes you. We distinguish aggregated, normal and sensitive personal data. Organisations collect personal data in different ways.",
  "learn_more": "click pentru detalii",
  "receive_from_you": "primim din partea dumneavostră",
  "aggregated_data": "date agregate",
  "personal_data": "Date personale",
  "sensitive_data": "Date personale sensibile",
  "receive_from_others": "primim din partea altora",
  "observe": "Observăm",
  "create": "deriva",
  "purchase": "achiziționa",
  "location": "locație",
  "section_location_explanation": "Personal data could be processed on different locations. In the EU, the GDPR is in place. If data about you is processed outside the EU, the laws of those countries may apply to the data too.",
  "all_data": "Toate datele",
  "most_data": "Majoritatea datelor",
  "some_data": "O parte din datele",
  "a_little_data": "O mică parte din datele",
  "least_amount_of_data": "cea mai mică",
  "no_data": "nicio dată",
  "none": "none",
  "processed_outside_the_eu": "Este prelucrat în afara U.E.",
  "duration": "durată",
  "section_duration_explanation": "Once personal data is collected you should know that organisations cannot store it indefinitely. The rule of thumb here is: you must not keep personal data for longer than you need it for the goal its collected.",
  "1_year_or_less": "one year or less",
  "1_month_or_less": "o lună sau mai puțin",
  "10_years_or_less": "ten years or less",
  "more_than_10_years": "more than 10 years",
  "purpose": "Utilizare",
  "section_purpose_explanation": "When an organisation wants to process information about you, they need a specific goal to do so. Personal data may not be used for other purposes than its collect for initially.",
  "human_resources": "Resurse umane",
  "providing_goods_and_services": "furnizare de bunuri și servicii",
  "scientific_research": "cercetare științifică",
  "financial_administration": "financiare",
  "health_care": "asistență medicală",
  "crime_and_national_security": "criminalitate și siguranța națională",
  "security_and_surveillance": "securitate și supraveghere",
  "marketing_or_sales_or_customer_relations": "marketing, vânzări și relația cu clientul",
  "authorisation_management": "managamentul autorizării",
  "judicial": "judiciar",
  "education": "education",
  "automated_decision_making": "Proces decizional automatizat",
  "fraud_detection_and_prevention": "detectarea și prevenirea fraudei",
  "legal": "Temei legal",
  "section_legal_explanation": "If an organisation wants to process data about you, they need to have a specific goal and a lawful basis. The lawful basis is the foundation for data processing under the GDPR. There are 6 lawful bases to base a processing activity.",
  "legal_obligation": "obligație legală",
  "contract": "contract",
  "consent": "consimțământ",
  "legitimate_interests": "interes legitim",
  "vital_interests": "interes vital",
  "public_task": "sarcină publică",
  "sharing": "Acces la date",
  "section_sharing_explanation": "Organisations can also share personal data with other organisations. This can be done for the execution of a task, or for a collaboration. Sometimes data must be shared because of a government. Or data can be sold to another organisation.",
  "customers": "clienți",
  "parent_or_daughter_or_sibling_organisation": "parent, daughter or sibling organisation",
  "processors": "persoane împuternicite de operatori",
  "advertisers": "agenți de publicitate",
  "government": "government",
  "third_parties": "terțe părți",
  "partners": "partners",
  "service_providers": "furnizori de servicii",
  "action": "A lua măsuri",
  "section_action_explanation": "If an organisation wants to process data about you, you have the right to information and other fundamental rights. You can find information in the privacy statement. You can also contact the organisation.",
  "read_our_privacy_policy": "Citiți politica noastră de confidențialitate",
  "manage_your_data": "Gestionați--vă datele",
  "contact_our_privacy_officer": "contact our privacy representative",
  "email": "email",
  "phone": "phone",
  "last_updated": "Ultima actualizare",
  "version": "version"
}
};